// ----------------------------------------------------------------------
// GENERATED FILE - do not edit by hand.
//
// Blog posts (slugs, titles, excerpts, dates, tags, SVG illustration refs).
//
// Source: live Directus CMS state via `bun run export:fallbacks`
// (apps/cms/scripts/export-fallbacks.ts). Regenerated on every build via
// apps/web's `prebuild` hook. Commits surface as CMS-content diffs.
// ----------------------------------------------------------------------

import type { BlogPost } from '$lib/types';

export const blogPosts: readonly BlogPost[] = [
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'Six people shared one computer. My weekend turn began at eight. Years later, failing to build one useful app pushed me into computer science.',
		external: false,
		lang: 'en',
		seoDescription: 'How a shared family computer, Ubuntu 9.04, a first website, and one failed app eventually pushed me to study computer science.',
		seoTitle: 'The Two-Hour Internet Slot That Led Me to Computer Science',
		slug: 'the-two-hour-internet-slot',
		svg: 'personal-telescope',
		tags: [
			'personal-story',
			'computer-science',
			'ubuntu',
			'web-development',
		],
		title: 'The two-hour internet slot',
		url: '/blog/the-two-hour-internet-slot',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'Accounting made no sense to me for two years. Then one conversation revealed the system underneath the rules.',
		external: false,
		lang: 'en',
		seoDescription: 'How two years of accounting confusion turned into one breakthrough, and why I stay close to difficult systems until their structure becomes visible.',
		seoTitle: 'How I Learn: Orbiting a System Until It Clicks',
		slug: 'how-i-learn-orbiting-a-system-until-it-clicks',
		svg: 'personal-train',
		tags: ['learning', 'systems-thinking', 'accounting', 'ai'],
		title: 'How I learn: orbiting a system until it clicks',
		url: '/blog/how-i-learn-orbiting-a-system-until-it-clicks',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'I see rows and columns when I look at systems. That habit helped me build a transit project, and taught me where data stops.',
		external: false,
		lang: 'en',
		seoDescription: 'How I use rows, columns, GTFS data, SQL, and accounting relationships to examine systems, plus the point where measurement stops.',
		seoTitle: 'Thinking in Matrices: From GTFS Data to SQL',
		slug: 'thinking-in-matrices',
		svg: 'personal-train',
		tags: ['systems-thinking', 'sql', 'gtfs', 'transit-data'],
		title: 'Thinking in matrices',
		url: '/blog/thinking-in-matrices',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'Claude was the primary implementation tool for my two sites. Codex mostly reviewed the work and sometimes stepped in as a backup implementer. I chose the architecture and caught the kind of CMS mistake a demo can hide.',
		external: false,
		lang: 'en',
		seoDescription: 'My real AI-assisted development workflow: I choose architecture, direct implementation, inspect the files, catch mistakes, and own what ships.',
		seoTitle: 'AI-Accelerated, Human-Owned: My Development Workflow',
		slug: 'ai-accelerated-human-owned-my-actual-workflow',
		svg: 'pro-database',
		tags: [
			'ai-assisted-development',
			'software-architecture',
			'cms',
			'code-review',
		],
		title: 'AI-accelerated, human-owned: my actual workflow',
		url: '/blog/ai-accelerated-human-owned-my-actual-workflow',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'Transit\'s managed database and worker cost me about $50 to $60 a month. In my PAYG account, the Oracle A1 VM that replaced them currently costs me $0, and its 200 GB-class disk forced an explicit retention budget.',
		external: false,
		lang: 'en',
		seoDescription: 'How I moved Transit\'s database and worker to an Oracle A1 VM at $0 monthly VM cost, with explicit retention, backup, and recovery tradeoffs.',
		seoTitle: '$50 to $0: Running Transit on Oracle Always Free',
		slug: '50-to-0-an-oracle-always-free-vm',
		svg: 'pro-pipeline',
		tags: [
			'oracle-cloud',
			'self-hosting',
			'postgresql',
			'transit-data',
		],
		title: '$50 to $0: an Oracle Always Free VM',
		url: '/blog/50-to-0-an-oracle-always-free-vm',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'If updates can take a few minutes to go live, you can separate the editor from the public site, keep published pages independent from the CMS, and give the owner one place to edit content.',
		external: false,
		lang: 'en',
		seoDescription: 'A practical guide for business owners deciding whether instant publishing or a build-time CMS workflow better fits their website.',
		seoTitle: 'Does Your Website Need Instant Publishing?',
		slug: 'does-your-website-need-instant-publishing',
		svg: 'pro-pipeline',
		tags: ['web-development', 'cms', 'sveltekit', 'directus'],
		title: 'Does your website need instant publishing?',
		url: '/blog/does-your-website-need-instant-publishing',
	},
];
