// ----------------------------------------------------------------------
// GENERATED FILE - do not edit by hand.
//
// Blog posts (slugs, titles, excerpts, dates, tags, SVG illustration refs).
//
// Source: live Directus CMS state via `bun run export:fallbacks`
// (apps/cms/scripts/export-fallbacks.ts). Regenerated on every build via
// apps/web's `prebuild` hook. Commits surface as CMS-content diffs.
// ----------------------------------------------------------------------

import type { BlogPost } from '$lib/types';

export const blogPosts: readonly BlogPost[] = [
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '2c41a9a0-34aa-4e3b-b333-5e6dcd53497c',
		coverImageAlt: 'STM network map and reported positions. Browser capture, 8 October 2026.',
		date: '2026-10-08',
		excerpt: 'One small message in Transit captures a much larger part of the data work: OC Transpo service alerts are unavailable because no alert feed is connected here.',
		external: false,
		lang: 'en',
		seoDescription: 'One small message in Transit captures a much larger part of the data work: OC Transpo service alerts are unavailable because no alert feed is connected here.',
		seoTitle: 'Missing data is not zero',
		slug: 'missing-data-is-not-zero',
		svg: 'pro-chart',
		tags: ['transit-data', 'analytics'],
		title: 'Missing data is not zero',
		translationKey: 'missing-data-is-not-zero',
		url: '/blog/missing-data-is-not-zero',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '2c41a9a0-34aa-4e3b-b333-5e6dcd53497c',
		coverImageAlt: 'STM network map and reported positions. Browser capture, 8 October 2026.',
		date: '2026-10-08',
		excerpt: 'En Transit hay un mensaje pequeño que resume una parte importante del trabajo con los datos: los avisos de servicio de OC Transpo no están disponibles porque no hay un flujo de avisos conectado.',
		external: false,
		lang: 'es',
		seoDescription: 'En Transit hay un mensaje pequeño que resume una parte importante del trabajo con los datos: los avisos de servicio de OC Transpo no están disponibles porque no hay un flujo de avisos conectado.',
		seoTitle: 'Un dato que falta no equivale a cero',
		slug: 'un-dato-que-falta-no-equivale-a-cero',
		svg: 'pro-chart',
		tags: ['transit-data', 'analytics'],
		title: 'Un dato que falta no equivale a cero',
		translationKey: 'missing-data-is-not-zero',
		url: '/blog/un-dato-que-falta-no-equivale-a-cero',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '2c41a9a0-34aa-4e3b-b333-5e6dcd53497c',
		coverImageAlt: 'STM network map and reported positions. Browser capture, 8 October 2026.',
		date: '2026-10-08',
		excerpt: 'Dans Transit, un petit message résume une bonne partie du travail sur les données : les avis de service d’OC Transpo sont indisponibles parce qu’aucun flux d’avis n’est connecté ici.',
		external: false,
		lang: 'fr',
		seoDescription: 'Dans Transit, un petit message résume une bonne partie du travail sur les données : les avis de service d’OC Transpo sont indisponibles parce qu’aucun flux d’avis n’est connecté ici.',
		seoTitle: 'Une donnée absente n’est pas un zéro',
		slug: 'une-donnee-absente-nest-pas-un-zero',
		svg: 'pro-chart',
		tags: ['transit-data', 'analytics'],
		title: 'Une donnée absente n’est pas un zéro',
		translationKey: 'missing-data-is-not-zero',
		url: '/blog/une-donnee-absente-nest-pas-un-zero',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '4b396e9c-b5b5-4a24-b5a4-c8cce0a2063d',
		coverImageAlt: 'Café Arona’s Shopify development storefront, 8 October 2026. Client handover remains ahead.',
		date: '2026-10-08',
		excerpt: 'Un site peut présenter une entreprise avant d’inclure un catalogue complet. Le site actuel de Café Arona est informatif et permet de prendre contact. Un catalogue pourra s’ajouter plus tard.',
		external: false,
		lang: 'fr',
		seoDescription: 'Ce qu’on peut préparer avant le catalogue définitif : une structure de contenu, des pages modifiables, des composants réutilisables et des responsabilités claires.',
		seoTitle: 'Avant d’avoir son catalogue définitif',
		slug: 'ce-quon-peut-preparer-avant-davoir-son-catalogue-definitif',
		svg: 'pro-pipeline',
		tags: ['web-development', 'e-commerce'],
		title: 'Ce qu’on peut préparer avant d’avoir son catalogue définitif',
		translationKey: 'before-product-catalogue-final',
		url: '/blog/ce-quon-peut-preparer-avant-davoir-son-catalogue-definitif',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '4b396e9c-b5b5-4a24-b5a4-c8cce0a2063d',
		coverImageAlt: 'Café Arona’s Shopify development storefront, 8 October 2026. Client handover remains ahead.',
		date: '2026-10-08',
		excerpt: 'Un sitio puede presentar una empresa antes de incluir un catálogo completo. El sitio actual de Café Arona es informativo y permite ponerse en contacto. El catálogo se puede agregar más adelante.',
		external: false,
		lang: 'es',
		seoDescription: 'Qué se puede preparar antes del catálogo definitivo: estructura de contenido, páginas editables, componentes reutilizables y responsabilidades claras.',
		seoTitle: 'Antes de tener el catálogo definitivo',
		slug: 'que-se-puede-avanzar-antes-de-tener-el-catalogo-definitivo',
		svg: 'pro-pipeline',
		tags: ['web-development', 'e-commerce'],
		title: 'Qué se puede avanzar antes de tener el catálogo definitivo',
		translationKey: 'before-product-catalogue-final',
		url: '/blog/que-se-puede-avanzar-antes-de-tener-el-catalogo-definitivo',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '4b396e9c-b5b5-4a24-b5a4-c8cce0a2063d',
		coverImageAlt: 'Café Arona’s Shopify development storefront, 8 October 2026. Client handover remains ahead.',
		date: '2026-10-08',
		excerpt: 'A website can present a business before it includes a complete product catalogue. Café Arona’s current site focuses on information and contact. A catalogue can be added later.',
		external: false,
		lang: 'en',
		seoDescription: 'What a website team can prepare before a product catalogue is final: content structure, editable pages, reusable components and clear responsibilities.',
		seoTitle: 'Before the product catalogue is final',
		slug: 'what-can-move-forward-before-the-product-catalogue-is-final',
		svg: 'pro-pipeline',
		tags: ['web-development', 'e-commerce'],
		title: 'What can move forward before the product catalogue is final?',
		translationKey: 'before-product-catalogue-final',
		url: '/blog/what-can-move-forward-before-the-product-catalogue-is-final',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '2d257b93-bb5c-451a-9f2e-143291d881ad',
		coverImageAlt: 'Component Gallery desktop dark reference. Full-page browser-test image; capture date unknown. Demonstration, not a production-site capture.',
		date: '2026-10-08',
		excerpt: 'Dos tarjetas pueden parecer de la misma familia y necesitar contratos distintos.',
		external: false,
		lang: 'es',
		seoDescription: 'Dos tarjetas pueden parecer de la misma familia y necesitar contratos distintos.',
		seoTitle: 'Cuándo dos componentes parecidos deberían seguir separados',
		slug: 'cuando-dos-componentes-parecidos-deberian-seguir-separados',
		svg: 'pro-code',
		tags: ['software-architecture', 'web-development'],
		title: 'Cuándo dos componentes parecidos deberían seguir separados',
		translationKey: 'when-similar-components-stay-separate',
		url: '/blog/cuando-dos-componentes-parecidos-deberian-seguir-separados',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '2d257b93-bb5c-451a-9f2e-143291d881ad',
		coverImageAlt: 'Component Gallery desktop dark reference. Full-page browser-test image; capture date unknown. Demonstration, not a production-site capture.',
		date: '2026-10-08',
		excerpt: 'Deux cartes peuvent avoir un air de famille et répondre à des exigences différentes.',
		external: false,
		lang: 'fr',
		seoDescription: 'Deux cartes peuvent avoir un air de famille et répondre à des exigences différentes.',
		seoTitle: 'Quand deux composants semblables devraient rester séparés',
		slug: 'quand-deux-composants-semblables-devraient-rester-separes',
		svg: 'pro-code',
		tags: ['software-architecture', 'web-development'],
		title: 'Quand deux composants semblables devraient rester séparés',
		translationKey: 'when-similar-components-stay-separate',
		url: '/blog/quand-deux-composants-semblables-devraient-rester-separes',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '2d257b93-bb5c-451a-9f2e-143291d881ad',
		coverImageAlt: 'Component Gallery desktop dark reference. Full-page browser-test image; capture date unknown. Demonstration, not a production-site capture.',
		date: '2026-10-08',
		excerpt: 'Two cards can look related and still need different contracts.',
		external: false,
		lang: 'en',
		seoDescription: 'Two cards can look related and still need different contracts.',
		seoTitle: 'When two similar components should stay separate',
		slug: 'when-two-similar-components-should-stay-separate',
		svg: 'pro-code',
		tags: ['software-architecture', 'web-development'],
		title: 'When two similar components should stay separate',
		translationKey: 'when-similar-components-stay-separate',
		url: '/blog/when-two-similar-components-should-stay-separate',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '42024627-5dab-496e-9d69-18387300802e',
		coverImageAlt: 'French tools page on yesid.dev, desktop browser capture, 8 October 2026.',
		date: '2026-10-08',
		excerpt: 'Un sitio multilingüe necesita algo más que títulos traducidos. También importa conservar el punto de lectura, los filtros elegidos y el mensaje que alguien está escribiendo.',
		external: false,
		lang: 'es',
		seoDescription: 'Un sitio multilingüe necesita algo más que títulos traducidos. También importa conservar el punto de lectura, los filtros elegidos y el mensaje que alguien está escribiendo.',
		seoTitle: 'Cambiar de idioma sin empezar de nuevo',
		slug: 'cambiar-de-idioma-sin-empezar-de-nuevo',
		svg: 'pro-code',
		tags: ['web-development', 'bilingual'],
		title: 'Cambiar de idioma sin empezar de nuevo',
		translationKey: 'changing-language-without-starting-over',
		url: '/blog/cambiar-de-idioma-sin-empezar-de-nuevo',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '42024627-5dab-496e-9d69-18387300802e',
		coverImageAlt: 'French tools page on yesid.dev, desktop browser capture, 8 October 2026.',
		date: '2026-10-08',
		excerpt: 'Un site multilingue ne se limite pas à traduire ses titres. Il faut aussi penser à la position de lecture, aux filtres choisis et au message en cours.',
		external: false,
		lang: 'fr',
		seoDescription: 'Un site multilingue ne se limite pas à traduire ses titres. Il faut aussi penser à la position de lecture, aux filtres choisis et au message en cours.',
		seoTitle: 'Changer de langue sans recommencer',
		slug: 'changer-de-langue-sans-recommencer',
		svg: 'pro-code',
		tags: ['web-development', 'bilingual'],
		title: 'Changer de langue sans recommencer',
		translationKey: 'changing-language-without-starting-over',
		url: '/blog/changer-de-langue-sans-recommencer',
	},
	{
		animation: 'draw',
		category: 'professional',
		coverImage: '42024627-5dab-496e-9d69-18387300802e',
		coverImageAlt: 'French tools page on yesid.dev, desktop browser capture, 8 October 2026.',
		date: '2026-10-08',
		excerpt: 'A multilingual website has more to translate than its headings. The reader\'s place, selected filters, and unfinished message also deserve attention.',
		external: false,
		lang: 'en',
		seoDescription: 'A multilingual website has more to translate than its headings. The reader\'s place, selected filters, and unfinished message also deserve attention.',
		seoTitle: 'Changing language should not mean starting over',
		slug: 'changing-language-should-not-mean-starting-over',
		svg: 'pro-code',
		tags: ['web-development', 'bilingual'],
		title: 'Changing language should not mean starting over',
		translationKey: 'changing-language-without-starting-over',
		url: '/blog/changing-language-should-not-mean-starting-over',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'If updates can take a few minutes to go live, you can separate the editor from the public site, keep published pages independent from the CMS, and give the owner one place to edit content.',
		external: false,
		lang: 'en',
		seoDescription: 'A practical guide for business owners deciding whether instant publishing or a build-time CMS workflow better fits their website.',
		seoTitle: 'Does Your Website Need Instant Publishing?',
		slug: 'does-your-website-need-instant-publishing',
		svg: 'pro-pipeline',
		tags: ['web-development', 'cms', 'sveltekit', 'directus'],
		title: 'Does your website need instant publishing?',
		translationKey: 'does-your-website-need-instant-publishing',
		url: '/blog/does-your-website-need-instant-publishing',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'Si las actualizaciones pueden tardar unos minutos en publicarse, puedes separar el editor del sitio público, mantener las páginas publicadas independientes del CMS y darle al propietario un solo lugar para editar el contenido.',
		external: false,
		lang: 'es',
		seoDescription: 'Una guía práctica para propietarios de negocios que deciden entre publicación instantánea y un flujo de CMS con compilación previa.',
		seoTitle: '¿Tu sitio web necesita publicación instantánea?',
		slug: 'tu-sitio-web-necesita-publicacion-instantanea',
		svg: 'pro-pipeline',
		tags: ['web-development', 'cms', 'sveltekit', 'directus'],
		title: '¿Tu sitio web necesita publicación instantánea?',
		translationKey: 'does-your-website-need-instant-publishing',
		url: '/blog/tu-sitio-web-necesita-publicacion-instantanea',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-11',
		dateModified: '2026-07-11',
		excerpt: 'Si les mises à jour peuvent prendre quelques minutes avant d’être mises en ligne, vous pouvez séparer l’éditeur du site public, garder les pages publiées indépendantes du CMS et offrir au propriétaire un seul endroit pour modifier le contenu.',
		external: false,
		lang: 'fr',
		seoDescription: 'Un guide pratique pour choisir entre la publication instantanée et un processus CMS qui publie après compilation.',
		seoTitle: 'Votre site web a-t-il besoin d’une publication instantanée?',
		slug: 'votre-site-web-a-t-il-besoin-dune-publication-instantanee',
		svg: 'pro-pipeline',
		tags: ['web-development', 'cms', 'sveltekit', 'directus'],
		title: 'Votre site web a-t-il besoin d’une publication instantanée?',
		translationKey: 'does-your-website-need-instant-publishing',
		url: '/blog/votre-site-web-a-t-il-besoin-dune-publication-instantanee',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-03',
		dateModified: '2026-07-11',
		excerpt: 'Transit\'s managed database and worker cost me about $50 to $60 a month. In my PAYG account, the Oracle A1 VM that replaced them currently costs me $0, and its 200 GB-class disk forced an explicit retention budget.',
		external: false,
		lang: 'en',
		seoDescription: 'How I moved Transit\'s database and worker to an Oracle A1 VM at $0 monthly VM cost, with explicit retention, backup, and recovery tradeoffs.',
		seoTitle: '$50 to $0: Running Transit on Oracle Always Free',
		slug: '50-to-0-an-oracle-always-free-vm',
		svg: 'pro-pipeline',
		tags: [
			'oracle-cloud',
			'self-hosting',
			'postgresql',
			'transit-data',
		],
		title: '$50 to $0: an Oracle Always Free VM',
		translationKey: '50-to-0-an-oracle-always-free-vm',
		url: '/blog/50-to-0-an-oracle-always-free-vm',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-03',
		dateModified: '2026-07-11',
		excerpt: 'La base de datos administrada y el worker de Transit me costaban entre 50 $ y 60 $ al mes. En mi cuenta PAYG, la VM Oracle A1 que los reemplazó me cuesta actualmente 0 $, y su disco de unos 200 GB me obligó a definir un presupuesto explícito de retención.',
		external: false,
		lang: 'es',
		seoDescription: 'Cómo trasladé la base de datos y el worker de Transit a una VM Oracle A1 de 0 $ al mes, con contrapartidas claras de retención, respaldo y recuperación.',
		seoTitle: 'De 50 $ a 0 $: Transit en Oracle Always Free',
		slug: 'de-50-a-0-una-vm-oracle-always-free',
		svg: 'pro-pipeline',
		tags: [
			'oracle-cloud',
			'self-hosting',
			'postgresql',
			'transit-data',
		],
		title: 'De 50 $ a 0 $: una VM Oracle Always Free',
		translationKey: '50-to-0-an-oracle-always-free-vm',
		url: '/blog/de-50-a-0-una-vm-oracle-always-free',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-07-03',
		dateModified: '2026-07-11',
		excerpt: 'La base de données gérée et le worker de Transit me coûtaient environ 50 à 60 $ par mois. Dans mon compte PAYG, la VM Oracle A1 qui les a remplacés me coûte actuellement 0 $, et son disque d’environ 200 Go m’a forcé à définir un budget de rétention explicite.',
		external: false,
		lang: 'fr',
		seoDescription: 'Comment j’ai déplacé la base de données et le worker de Transit vers une VM Oracle A1 à 0 $ par mois, avec des compromis explicites de rétention, de sauvegarde et de reprise.',
		seoTitle: 'De 50 $ à 0 $ : faire tourner Transit sur Oracle Always Free',
		slug: 'de-50-a-0-une-vm-oracle-always-free',
		svg: 'pro-pipeline',
		tags: [
			'oracle-cloud',
			'self-hosting',
			'postgresql',
			'transit-data',
		],
		title: 'De 50 $ à 0 $ : une VM Oracle Always Free',
		translationKey: '50-to-0-an-oracle-always-free-vm',
		url: '/blog/de-50-a-0-une-vm-oracle-always-free',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-06-25',
		dateModified: '2026-07-11',
		excerpt: 'Claude était mon principal outil d’implémentation pour mes deux sites. Codex révisait surtout le travail et prenait parfois le relais pour l’implémentation. J’ai choisi l’architecture et repéré le genre d’erreur liée au CMS qu’une démo peut cacher.',
		external: false,
		lang: 'fr',
		seoDescription: 'Mon vrai flux avec l’IA : je choisis l’architecture, dirige l’implémentation, inspecte les fichiers, repère les erreurs et assume ce qui est livré.',
		seoTitle: 'Accéléré par l’IA, piloté par l’humain : mon flux de travail',
		slug: 'accelere-par-lia-pilote-par-lhumain-mon-vrai-flux-de-travail',
		svg: 'pro-database',
		tags: [
			'ai-assisted-development',
			'software-architecture',
			'cms',
			'code-review',
		],
		title: 'Accéléré par l’IA, piloté par l’humain : mon vrai flux de travail',
		translationKey: 'ai-accelerated-human-owned-my-actual-workflow',
		url: '/blog/accelere-par-lia-pilote-par-lhumain-mon-vrai-flux-de-travail',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-06-25',
		dateModified: '2026-07-11',
		excerpt: 'Claude fue mi principal herramienta de implementación para mis dos sitios. Codex se encargó sobre todo de revisar el trabajo y, a veces, intervino como implementador de respaldo. Yo elegí la arquitectura y detecté el tipo de error relacionado con el CMS que una demo puede ocultar.',
		external: false,
		lang: 'es',
		seoDescription: 'Mi flujo real con IA: elijo la arquitectura, dirijo la implementación, inspecciono archivos, detecto errores y respondo por lo que publico.',
		seoTitle: 'Acelerado por IA, en manos humanas: mi flujo de trabajo real',
		slug: 'acelerado-por-ia-en-manos-humanas-mi-flujo-de-trabajo-real',
		svg: 'pro-database',
		tags: [
			'ai-assisted-development',
			'software-architecture',
			'cms',
			'code-review',
		],
		title: 'Acelerado por IA, en manos humanas: mi flujo de trabajo real',
		translationKey: 'ai-accelerated-human-owned-my-actual-workflow',
		url: '/blog/acelerado-por-ia-en-manos-humanas-mi-flujo-de-trabajo-real',
	},
	{
		animation: 'morph',
		category: 'professional',
		date: '2026-06-25',
		dateModified: '2026-07-11',
		excerpt: 'Claude was the primary implementation tool for my two sites. Codex mostly reviewed the work and sometimes stepped in as a backup implementer. I chose the architecture and caught the kind of CMS mistake a demo can hide.',
		external: false,
		lang: 'en',
		seoDescription: 'My real AI-assisted development workflow: I choose architecture, direct implementation, inspect the files, catch mistakes, and own what ships.',
		seoTitle: 'AI-Accelerated, Human-Owned: My Development Workflow',
		slug: 'ai-accelerated-human-owned-my-actual-workflow',
		svg: 'pro-database',
		tags: [
			'ai-assisted-development',
			'software-architecture',
			'cms',
			'code-review',
		],
		title: 'AI-accelerated, human-owned: my actual workflow',
		translationKey: 'ai-accelerated-human-owned-my-actual-workflow',
		url: '/blog/ai-accelerated-human-owned-my-actual-workflow',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-17',
		dateModified: '2026-07-11',
		excerpt: 'Veo filas y columnas cuando observo sistemas. Ese hábito me ayudó a construir un proyecto de transporte público y me enseñó dónde terminan los datos.',
		external: false,
		lang: 'es',
		seoDescription: 'Cómo uso filas, columnas, datos GTFS, SQL y relaciones contables para examinar sistemas y reconocer dónde termina la medición.',
		seoTitle: 'Pensar en matrices: de los datos GTFS a las consultas SQL',
		slug: 'pensar-en-matrices',
		svg: 'personal-train',
		tags: ['systems-thinking', 'sql', 'gtfs', 'transit-data'],
		title: 'Pensar en matrices',
		translationKey: 'thinking-in-matrices',
		url: '/blog/pensar-en-matrices',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-17',
		dateModified: '2026-07-11',
		excerpt: 'Je vois des lignes et des colonnes quand j’observe les systèmes. Cette habitude m’a aidé à bâtir un projet de transport collectif et m’a appris où les données s’arrêtent.',
		external: false,
		lang: 'fr',
		seoDescription: 'Comment j’utilise les lignes, les colonnes, les données GTFS, SQL et les relations comptables pour examiner des systèmes et voir où la mesure s’arrête.',
		seoTitle: 'Penser en matrices : des données GTFS aux requêtes SQL',
		slug: 'penser-en-matrices',
		svg: 'personal-train',
		tags: ['systems-thinking', 'sql', 'gtfs', 'transit-data'],
		title: 'Penser en matrices',
		translationKey: 'thinking-in-matrices',
		url: '/blog/penser-en-matrices',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-17',
		dateModified: '2026-07-11',
		excerpt: 'I see rows and columns when I look at systems. That habit helped me build a transit project, and taught me where data stops.',
		external: false,
		lang: 'en',
		seoDescription: 'How I use rows, columns, GTFS data, SQL, and accounting relationships to examine systems, plus the point where measurement stops.',
		seoTitle: 'Thinking in Matrices: From GTFS Data to SQL',
		slug: 'thinking-in-matrices',
		svg: 'personal-train',
		tags: ['systems-thinking', 'sql', 'gtfs', 'transit-data'],
		title: 'Thinking in matrices',
		translationKey: 'thinking-in-matrices',
		url: '/blog/thinking-in-matrices',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-09',
		dateModified: '2026-07-11',
		excerpt: 'Pendant deux ans, la comptabilité n’avait aucun sens pour moi. Puis une conversation m’a révélé le système derrière les règles.',
		external: false,
		lang: 'fr',
		seoDescription: 'Deux années de confusion en comptabilité ont mené à un déclic. Voici pourquoi je reste au contact des systèmes difficiles jusqu’à voir leur structure.',
		seoTitle: 'Comment j’apprends : rester au contact jusqu’au déclic',
		slug: 'comment-japprends-graviter-autour-dun-systeme-jusquau-declic',
		svg: 'personal-train',
		tags: ['learning', 'systems-thinking', 'accounting', 'ai'],
		title: 'Comment j’apprends : graviter autour d’un système jusqu’au déclic',
		translationKey: 'how-i-learn-orbiting-a-system-until-it-clicks',
		url: '/blog/comment-japprends-graviter-autour-dun-systeme-jusquau-declic',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-09',
		dateModified: '2026-07-11',
		excerpt: 'Durante dos años, la contabilidad no tenía sentido para mí. Luego, una conversación reveló el sistema que había detrás de las reglas.',
		external: false,
		lang: 'es',
		seoDescription: 'Cómo dos años de confusión con la contabilidad terminaron en un momento en que todo encajó, y por qué sigo cerca de los sistemas difíciles hasta ver su estructura.',
		seoTitle: 'Cómo aprendo: orbitar un sistema hasta que encaja',
		slug: 'como-aprendo-orbitar-un-sistema-hasta-que-encaja',
		svg: 'personal-train',
		tags: ['learning', 'systems-thinking', 'accounting', 'ai'],
		title: 'Cómo aprendo: orbitar un sistema hasta que encaja',
		translationKey: 'how-i-learn-orbiting-a-system-until-it-clicks',
		url: '/blog/como-aprendo-orbitar-un-sistema-hasta-que-encaja',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-09',
		dateModified: '2026-07-11',
		excerpt: 'Accounting made no sense to me for two years. Then one conversation revealed the system underneath the rules.',
		external: false,
		lang: 'en',
		seoDescription: 'How two years of accounting confusion turned into one breakthrough, and why I stay close to difficult systems until their structure becomes visible.',
		seoTitle: 'How I Learn: Orbiting a System Until It Clicks',
		slug: 'how-i-learn-orbiting-a-system-until-it-clicks',
		svg: 'personal-train',
		tags: ['learning', 'systems-thinking', 'accounting', 'ai'],
		title: 'How I learn: orbiting a system until it clicks',
		translationKey: 'how-i-learn-orbiting-a-system-until-it-clicks',
		url: '/blog/how-i-learn-orbiting-a-system-until-it-clicks',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-01',
		dateModified: '2026-07-11',
		excerpt: 'Seis personas compartíamos una computadora. Mi turno de fin de semana empezaba a las ocho. Años después, no poder crear una sola aplicación útil me llevó a estudiar ciencias de la computación.',
		external: false,
		lang: 'es',
		seoDescription: 'Cómo una computadora familiar compartida, Ubuntu 9.04, un primer sitio web y una aplicación fallida terminaron por llevarme a estudiar informática.',
		seoTitle: 'Dos horas de internet que me llevaron a la informática',
		slug: 'el-turno-de-dos-horas-para-usar-internet',
		svg: 'personal-telescope',
		tags: [
			'personal-story',
			'computer-science',
			'ubuntu',
			'web-development',
		],
		title: 'El turno de dos horas para usar internet',
		translationKey: 'the-two-hour-internet-slot',
		url: '/blog/el-turno-de-dos-horas-para-usar-internet',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-01',
		dateModified: '2026-07-11',
		excerpt: 'Six personnes se partageaient un ordinateur. Mon tour de fin de semaine commençait à huit heures. Des années plus tard, mon incapacité à créer une seule application utile m’a poussé vers l’informatique.',
		external: false,
		lang: 'fr',
		seoDescription: 'Comment un ordinateur familial partagé, Ubuntu 9.04, un premier site web et l’échec d’une application m’ont finalement poussé à étudier l’informatique.',
		seoTitle: 'Deux heures d’internet qui m’ont mené à l’informatique',
		slug: 'le-creneau-internet-de-deux-heures',
		svg: 'personal-telescope',
		tags: [
			'personal-story',
			'computer-science',
			'ubuntu',
			'web-development',
		],
		title: 'Le créneau internet de deux heures',
		translationKey: 'the-two-hour-internet-slot',
		url: '/blog/le-creneau-internet-de-deux-heures',
	},
	{
		animation: 'morph',
		category: 'personal',
		date: '2026-06-01',
		dateModified: '2026-07-11',
		excerpt: 'Six people shared one computer. My weekend turn began at eight. Years later, failing to build one useful app pushed me into computer science.',
		external: false,
		lang: 'en',
		seoDescription: 'How a shared family computer, Ubuntu 9.04, a first website, and one failed app eventually pushed me to study computer science.',
		seoTitle: 'The Two-Hour Internet Slot That Led Me to Computer Science',
		slug: 'the-two-hour-internet-slot',
		svg: 'personal-telescope',
		tags: [
			'personal-story',
			'computer-science',
			'ubuntu',
			'web-development',
		],
		title: 'The two-hour internet slot',
		translationKey: 'the-two-hour-internet-slot',
		url: '/blog/the-two-hour-internet-slot',
	},
];
