import { defineAssetUsages } from "@repo/shared";

/**
 * Dynamic asset seams that cannot be proven from a single literal reference.
 *
 * Keep this module data-only. The repository scanner imports it in Node, so it
 * must not depend on SvelteKit runtime modules, environment variables, or I/O.
 */
export const assetUsageDeclarations = defineAssetUsages([
  {
    usageKey: "site.services.svg-glob",
    semanticKey: "site.services.svg-glob",
    consumerType: "service",
    consumerKey: "service-illustrations",
    source: "apps/web/src/lib/utils/service-svg.ts#RAW_SERVICE_SVGS",
    route: "/services",
    locale: null,
    slot: "illustration",
    required: true,
    deliveryMode: "inline-svg",
    confidence: "declared-dynamic",
    reason:
      "Service SVG filenames come from CMS-backed service records and resolve through a Vite glob.",
  },
  {
    usageKey: "site.blog.fallback-svg",
    semanticKey: "site.blog.fallback-svg",
    consumerType: "blog",
    consumerKey: "blog-fallbacks",
    source: "apps/web/src/lib/blog/static-helpers.ts#fallbackSvgs",
    route: "/blog",
    locale: null,
    slot: "header-art",
    required: false,
    deliveryMode: "inline-svg",
    confidence: "declared-dynamic",
    reason:
      "The post record chooses a fallback SVG key at runtime from a build-time glob.",
  },
  {
    usageKey: "site.projects.fallback-art",
    semanticKey: "site.projects.fallback-art",
    consumerType: "project",
    consumerKey: "project-card-fallback",
    source:
      "apps/web/src/lib/components/projects/ProjectCard.svelte#project-fallbacks",
    route: "/projects",
    locale: null,
    slot: "card-media",
    required: true,
    deliveryMode: "inline-svg",
    confidence: "declared-dynamic",
    reason:
      "The responsive project card selects one of two raw blueprint imports at render time.",
  },
  ...(["sign", "helmet", "barricade", "balise"] as const).map((name) => ({
    usageKey: `site.graffiti.prop-${name}`,
    semanticKey: `site.graffiti.prop-${name}`,
    consumerType: "component" as const,
    consumerKey: `closer-prop-${name}`,
    source: "apps/web/src/lib/components/home/CloserProps.svelte#propFiles",
    route: "/",
    locale: null,
    slot: `graffiti-prop-${name}`,
    required: true,
    deliveryMode: "inline-svg" as const,
    confidence: "declared-dynamic" as const,
    reason: `The fixed ${name} key is interpolated into the fetched graffiti prop SVG path.`,
  })),
  {
    usageKey: "site.og.localized-static",
    semanticKey: "site.og.localized-static",
    consumerType: "system",
    consumerKey: "localized-og-default",
    source: "apps/web/src/lib/utils/seo-defaults.ts#defaultOgImageFor",
    route: "/",
    locale: null,
    slot: "og-image",
    required: true,
    deliveryMode: "og-meta",
    confidence: "declared-dynamic",
    reason: "The locale suffix determines the committed default OG card path.",
  },
  {
    usageKey: "site.og.localized-route",
    semanticKey: "site.og.localized-route",
    consumerType: "route",
    consumerKey: "localized-route-og",
    source: "apps/web/src/lib/utils/seo-defaults.ts#localizeOgCard",
    route: null,
    locale: null,
    slot: "og-image",
    required: true,
    deliveryMode: "og-meta",
    confidence: "declared-dynamic",
    reason:
      "Published locale and route keys select the matching generated route OG sibling.",
  },
  {
    usageKey: "site.og.localized-service",
    semanticKey: "site.og.localized-service",
    consumerType: "service",
    consumerKey: "localized-service-og",
    source:
      "apps/web/src/lib/adapters/route-seo-factories.ts#servicesIdSeoFactory",
    route: "/services/[id]",
    locale: null,
    slot: "og-image",
    required: true,
    deliveryMode: "og-meta",
    confidence: "declared-dynamic",
    reason:
      "The service id composes a static OG path that is localized by the shared OG resolver.",
  },
  {
    usageKey: "site.og.runtime-blog",
    semanticKey: "site.og.runtime-blog",
    consumerType: "blog",
    consumerKey: "runtime-blog-og",
    source:
      "apps/web/src/lib/adapters/route-seo-factories.ts#blogSlugSeoFactory",
    route: "/blog/[slug]",
    locale: null,
    slot: "og-image",
    required: true,
    deliveryMode: "og-meta",
    confidence: "declared-dynamic",
    reason: "The blog slug and locale compose a runtime OG endpoint.",
  },
  {
    usageKey: "site.og.runtime-project",
    semanticKey: "site.og.runtime-project",
    consumerType: "project",
    consumerKey: "runtime-project-og",
    source:
      "apps/web/src/lib/adapters/route-seo-factories.ts#projectSlugSeoFactory",
    route: "/projects/[slug]",
    locale: null,
    slot: "og-image",
    required: true,
    deliveryMode: "og-meta",
    confidence: "declared-dynamic",
    reason: "The project slug and locale compose a runtime OG endpoint.",
  },
  {
    usageKey: "site.media.uuid-mirror",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "system",
    consumerKey: "directus-media-resolver",
    source: "apps/web/src/lib/directus/assets.ts#createAssets",
    route: null,
    locale: null,
    slot: "content-media",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "A Directus UUID resolves through the generated mirror map before the optional development fallback.",
  },
  {
    usageKey: "site.media.about-identity-headshot",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "component",
    consumerKey: "about-identity-headshot",
    source:
      "apps/web/src/lib/components/about/AboutIdentity.svelte#img-src:identity.headshot",
    route: "/about",
    locale: null,
    slot: "identity-headshot",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The about identity record selects a CMS-backed headshot and its generated responsive variants.",
  },
  {
    usageKey: "site.media.about-identity-headshot-srcset",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "component",
    consumerKey: "about-identity-headshot",
    source:
      "apps/web/src/lib/components/about/AboutIdentity.svelte#img-srcset:headshotSrcset",
    route: "/about",
    locale: null,
    slot: "identity-headshot-srcset",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The about identity record selects the generated responsive headshot variants.",
  },
  {
    usageKey: "site.media.about-polaroid",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "component",
    consumerKey: "about-polaroid-carousel",
    source:
      "apps/web/src/lib/components/about/AboutPolaroids.svelte#img-src:current.src",
    route: "/about",
    locale: null,
    slot: "polaroid-photo",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The active localized polaroid record determines the image rendered by the carousel.",
  },
  {
    usageKey: "site.media.about-language",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "component",
    consumerKey: "about-language-flags",
    source:
      "apps/web/src/lib/components/about/AboutLanguages.svelte#img-src:imageSrc",
    route: "/about",
    locale: null,
    slot: "language-flag",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "Each about language record can provide either a mirrored Directus identity or an explicit image URL.",
  },
  {
    usageKey: "site.projects.hero-primary",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "project",
    consumerKey: "project-hero-primary",
    source:
      "apps/web/src/lib/components/projects/ProjectHeroPreview.svelte#img-src:primaryImage?.src",
    route: "/projects/[slug]",
    locale: null,
    slot: "hero-primary",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The project record and active theme resolve the primary Directus image and responsive preset.",
  },
  {
    usageKey: "site.projects.hero-primary-srcset",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "project",
    consumerKey: "project-hero-primary",
    source:
      "apps/web/src/lib/components/projects/ProjectHeroPreview.svelte#img-srcset:primaryImage?.srcset",
    route: "/projects/[slug]",
    locale: null,
    slot: "hero-primary-srcset",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The project record and active theme resolve the primary responsive Directus image preset.",
  },
  {
    usageKey: "site.projects.hero-secondary",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "project",
    consumerKey: "project-hero-secondary",
    source:
      "apps/web/src/lib/components/projects/ProjectHeroPreview.svelte#img-src:secondaryImage?.src",
    route: "/projects/[slug]",
    locale: null,
    slot: "hero-secondary",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "An optional themed secondary Directus image supplies the narrow companion hero pane.",
  },
  {
    usageKey: "site.projects.hero-secondary-srcset",
    semanticKey: "site.media.uuid-mirror",
    consumerType: "project",
    consumerKey: "project-hero-secondary",
    source:
      "apps/web/src/lib/components/projects/ProjectHeroPreview.svelte#img-srcset:secondaryImage?.srcset",
    route: "/projects/[slug]",
    locale: null,
    slot: "hero-secondary-srcset",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The optional themed secondary image supplies its responsive Directus preset.",
  },
  {
    usageKey: "site.services.img-fallback",
    semanticKey: "site.services.svg-glob",
    consumerType: "service",
    consumerKey: "home-service-static-fallback",
    source:
      "apps/web/src/lib/components/home/HomeServices.svelte#img-src:/svg/services/{service.svg}",
    route: "/",
    locale: null,
    slot: "illustration-fallback",
    required: true,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The CMS service SVG filename is interpolated into the static fallback shown until inline enhancement succeeds.",
  },
  {
    usageKey: "site.cms.image-block",
    semanticKey: "site.cms.image-block",
    consumerType: "page-block",
    consumerKey: "editor-image-block",
    source:
      "apps/web/src/lib/components/cms/blocks/ImageBlock.svelte#img-src:source.src",
    route: null,
    locale: null,
    slot: "body-image",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "Editor.js image blocks supply Directus file identities from CMS content at runtime.",
  },
  {
    usageKey: "site.cms.image-block-srcset",
    semanticKey: "site.cms.image-block",
    consumerType: "page-block",
    consumerKey: "editor-image-block",
    source:
      "apps/web/src/lib/components/cms/blocks/ImageBlock.svelte#img-srcset:source.srcset",
    route: null,
    locale: null,
    slot: "body-image-srcset",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "Editor.js image blocks supply responsive Directus file variants from CMS content at runtime.",
  },
  {
    usageKey: "site.cms.project-gallery-thumbnail",
    semanticKey: "site.cms.image-block",
    consumerType: "project",
    consumerKey: "project-gallery-thumbnail",
    source:
      "apps/web/src/lib/components/projects/ProjectImageGallery.svelte#img-src:source.src",
    route: "/projects/[slug]",
    locale: null,
    slot: "gallery-thumbnail",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "Each CMS image block resolves its themed file identity into the gallery thumbnail preset.",
  },
  {
    usageKey: "site.cms.project-gallery-thumbnail-srcset",
    semanticKey: "site.cms.image-block",
    consumerType: "project",
    consumerKey: "project-gallery-thumbnail",
    source:
      "apps/web/src/lib/components/projects/ProjectImageGallery.svelte#img-srcset:source.srcset",
    route: "/projects/[slug]",
    locale: null,
    slot: "gallery-thumbnail-srcset",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason: "Each CMS image block resolves its responsive thumbnail variants.",
  },
  {
    usageKey: "site.cms.project-gallery-lightbox",
    semanticKey: "site.cms.image-block",
    consumerType: "project",
    consumerKey: "project-gallery-lightbox",
    source:
      "apps/web/src/lib/components/projects/ProjectImageGallery.svelte#img-src:activeSource?.src",
    route: "/projects/[slug]",
    locale: null,
    slot: "gallery-lightbox",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The selected CMS image block resolves its themed file identity into the lightbox preset.",
  },
  {
    usageKey: "site.cms.project-gallery-lightbox-srcset",
    semanticKey: "site.cms.image-block",
    consumerType: "project",
    consumerKey: "project-gallery-lightbox",
    source:
      "apps/web/src/lib/components/projects/ProjectImageGallery.svelte#img-srcset:activeSource?.srcset",
    route: "/projects/[slug]",
    locale: null,
    slot: "gallery-lightbox-srcset",
    required: false,
    deliveryMode: "local-img",
    confidence: "declared-dynamic",
    reason:
      "The selected CMS image block resolves its responsive lightbox variants.",
  },
]);
