import { describe, it, expect } from 'bun:test';
import {
	RouteSeoFixtureSchema,
	loadRouteSeoFixture,
	toRouteSeoRow,
	toRouteSeoPatch,
	toTranslationRows,
} from '../scripts/seed-route-seo';

describe('seed-route-seo pure helpers', () => {
	const fixture = loadRouteSeoFixture();
	const home = fixture.find((r) => r.path === '/')!;
	const about = fixture.find((r) => r.path === '/about')!;
	const blog = fixture.find((r) => r.path === '/blog')!;
	const techStack = fixture.find((r) => r.path === '/tech-stack')!;

	describe('loadRouteSeoFixture', () => {
		it('returns 8 rows (one per static route)', () => {
			expect(fixture.length).toBe(8);
		});

		it('every fixture parses cleanly through Zod (no throw on load)', () => {
			expect(fixture.length).toBeGreaterThan(0);
		});

		it('paths are unique', () => {
			const paths = fixture.map((r) => r.path);
			expect(new Set(paths).size).toBe(paths.length);
		});

		it('covers the 8 expected static routes', () => {
			const paths = fixture.map((r) => r.path).sort();
			expect(paths).toEqual(
				[
					'/',
					'/about',
					'/blog',
					'/blog/personal',
					'/contact',
					'/projects',
					'/services',
					'/tech-stack',
				].sort(),
			);
		});

		it('every row has at least 1 EN translation', () => {
			for (const r of fixture) {
				const en = r.translations.find((t) => t.languages_code === 'en');
				expect(en).toBeDefined();
			}
		});

		it('every row has a French translation for the FR-first SEO lock', () => {
			for (const r of fixture) {
				const fr = r.translations.find((t) => t.languages_code === 'fr');
				expect(fr?.title).toBeTruthy();
				expect(fr?.description).toBeTruthy();
			}
		});

		it('every row is published', () => {
			for (const r of fixture) {
				expect(r.status).toBe('published');
			}
		});

		it('sort values are unique 1–8', () => {
			const sorts = fixture.map((r) => r.sort).sort((a, b) => a - b);
			expect(sorts).toEqual([1, 2, 3, 4, 5, 6, 7, 8]);
		});

		it('every path starts with `/`', () => {
			for (const r of fixture) {
				expect(r.path).toMatch(/^\//);
			}
		});
	});

	describe('home `/` row', () => {
		it('exists with sort=1', () => {
			expect(home.sort).toBe(1);
		});

		it('uses a verbatim home title', () => {
			const en = home.translations.find((t) => t.languages_code === 'en');
			expect(en?.title).toBe('yesid. | Digital Infrastructure that Moves.');
		});

		it('home description is in 50-200 SEO band', () => {
			const en = home.translations.find((t) => t.languages_code === 'en');
			const len = (en?.description ?? '').length;
			expect(len).toBeGreaterThanOrEqual(50);
			expect(len).toBeLessThanOrEqual(200);
		});
	});

	describe('toRouteSeoRow', () => {
		it('preserves path, og_image, status, sort', () => {
			const row = toRouteSeoRow(about);
			expect(row.path).toBe('/about');
			expect(row.og_image).toBeNull();
			expect(row.status).toBe('published');
			expect(row.sort).toBe(2);
		});

		it('does not include `id` (auto-generated by Directus)', () => {
			const row = toRouteSeoRow(home) as Record<string, unknown>;
			expect(row.id).toBeUndefined();
		});

		it('includes nested translations array', () => {
			const row = toRouteSeoRow(blog);
			expect(row.translations.length).toBe(2);
			expect(row.translations[0]?.languages_code).toBe('en');
			expect(row.translations[0]?.title).toBe('Blog');
			expect(row.translations[1]?.languages_code).toBe('fr');
			expect(row.translations[1]?.title).toBe('Blog');
		});

		it('handles og_image=null correctly', () => {
			for (const f of fixture) {
				expect(toRouteSeoRow(f).og_image).toBeNull();
			}
		});
	});

	describe('toRouteSeoPatch', () => {
		it('returns scalar fields only (excludes path, translations, id)', () => {
			const patch = toRouteSeoPatch(about);
			expect(Object.keys(patch).sort()).toEqual(
				['og_image', 'sort', 'status'].sort(),
			);
		});

		it('preserves status, sort, og_image', () => {
			const patch = toRouteSeoPatch(techStack);
			expect(patch.status).toBe('published');
			expect(patch.sort).toBe(8);
			expect(patch.og_image).toBeNull();
		});
	});

	describe('toTranslationRows', () => {
		it('returns en and fr rows for each static route fixture', () => {
			expect(toTranslationRows(home).map((row) => row.languages_code)).toEqual(['en', 'fr']);
			expect(toTranslationRows(about).map((row) => row.languages_code)).toEqual(['en', 'fr']);
		});

		it('preserves languages_code, title, description', () => {
			const rows = toTranslationRows(about);
			expect(rows[0]?.languages_code).toBe('en');
			expect(rows[0]?.title).toBe('Yesid O., Digital Infrastructure Engineer in Montreal');
			expect((rows[0]?.description ?? '').length).toBeGreaterThan(0);
		});

		it('strips fixture-only fields', () => {
			const rows = toTranslationRows(home) as Record<string, unknown>[];
			expect(rows[0]?.['extra']).toBeUndefined();
		});
	});

	describe('Translation length bands', () => {
		it('every EN title is ≤70 chars', () => {
			for (const r of fixture) {
				const en = r.translations.find((t) => t.languages_code === 'en');
				if (en?.title != null) {
					expect(en.title.length).toBeLessThanOrEqual(70);
				}
			}
		});

		it('every EN description is in 50-200 SEO band', () => {
			for (const r of fixture) {
				const en = r.translations.find((t) => t.languages_code === 'en');
				if (en?.description != null) {
					const len = en.description.length;
					expect(len).toBeGreaterThanOrEqual(50);
					expect(len).toBeLessThanOrEqual(200);
				}
			}
		});

		it('every FR description is in 50-200 SEO band', () => {
			for (const r of fixture) {
				const fr = r.translations.find((t) => t.languages_code === 'fr');
				if (fr?.description != null) {
					const len = fr.description.length;
					expect(len).toBeGreaterThanOrEqual(50);
					expect(len).toBeLessThanOrEqual(200);
				}
			}
		});
	});

	describe('RouteSeoFixtureSchema rejects malformed input', () => {
		it('rejects path missing leading `/`', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: 'about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).toThrow();
		});

		it('rejects duplicate paths in fixture', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'a'.repeat(60),
							},
						],
					},
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 2,
						translations: [
							{
								languages_code: 'en',
								title: 'About 2',
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).toThrow(/unique/);
		});

		it('rejects invalid status enum value', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'invalid-status',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).toThrow();
		});

		it('rejects non-UUID og_image', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: 'not-a-uuid',
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).toThrow();
		});

		it('accepts og_image as a valid UUID', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: '74b62762-8d8d-4301-8635-f236bc23f739',
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).not.toThrow();
		});

		it('accepts null title (override absent → falls back to code-side default)', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: null,
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).not.toThrow();
		});

		it('accepts null description (override absent → falls back to siteSeoDefaults.defaultDescription)', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{ languages_code: 'en', title: 'About', description: null },
						],
					},
				]),
			).not.toThrow();
		});

		it('rejects title >70 chars', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'a'.repeat(71),
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).toThrow();
		});

		it('rejects description <50 chars (out of SEO band)', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'too short',
							},
						],
					},
				]),
			).toThrow();
		});

		it('rejects description >200 chars (out of SEO band)', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'en',
								title: 'About',
								description: 'a'.repeat(201),
							},
						],
					},
				]),
			).toThrow();
		});

		it('rejects empty translations array', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [],
					},
				]),
			).toThrow();
		});

		it('rejects empty fixture array', () => {
			expect(() => RouteSeoFixtureSchema.parse([])).toThrow();
		});

		it('rejects invalid languages_code', () => {
			expect(() =>
				RouteSeoFixtureSchema.parse([
					{
						path: '/about',
						og_image: null,
						status: 'published',
						sort: 1,
						translations: [
							{
								languages_code: 'de',
								title: 'About',
								description: 'a'.repeat(60),
							},
						],
					},
				]),
			).toThrow();
		});
	});
});
