/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    'tech-stack': TechStack;
    services: Service;
    projects: Project;
    'blog-posts': BlogPost;
    'stack-scenarios': StackScenario;
    users: User;
    media: Media;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'tech-stack': {
      relatedServices: 'services';
      relatedProjects: 'projects';
    };
    services: {
      relatedProjects: 'projects';
    };
  };
  collectionsSelect: {
    'tech-stack': TechStackSelect<false> | TechStackSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'stack-scenarios': StackScenariosSelect<false> | StackScenariosSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'es') | ('en' | 'fr' | 'es')[];
  globals: {
    'home-content': HomeContent;
    'services-page': ServicesPage;
    'projects-page': ProjectsPage;
    'blog-page': BlogPage;
    'tech-stack-page': TechStackPage;
    'about-content': AboutContent;
    'contact-content': ContactContent;
    'nav-links': NavLink;
    'error-pages': ErrorPage;
    'site-meta': SiteMeta;
  };
  globalsSelect: {
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'tech-stack-page': TechStackPageSelect<false> | TechStackPageSelect<true>;
    'about-content': AboutContentSelect<false> | AboutContentSelect<true>;
    'contact-content': ContactContentSelect<false> | ContactContentSelect<true>;
    'nav-links': NavLinksSelect<false> | NavLinksSelect<true>;
    'error-pages': ErrorPagesSelect<false> | ErrorPagesSelect<true>;
    'site-meta': SiteMetaSelect<false> | SiteMetaSelect<true>;
  };
  locale: 'en' | 'fr' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack".
 */
export interface TechStack {
  /**
   * Stable slug id, e.g. "postgresql". Matches yesid.dev tech IDs.
   */
  id: string;
  name: string;
  layer: 'data' | 'backend' | 'api' | 'frontend' | 'mobile' | 'analytics' | 'devops' | 'testing' | 'systems';
  domains?:
    | (
        | 'data-engineering'
        | 'web-development'
        | 'mobile-development'
        | 'analytics-bi'
        | 'systems-programming'
        | 'devops-infra'
        | 'internal-tooling'
      )[]
    | null;
  /**
   * Icon slug matching yesid.dev icon registry.
   */
  icon?: string | null;
  proficiency?: ('expert' | 'proficient' | 'familiar') | null;
  relatedServices?: {
    docs?: (string | Service)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  relatedProjects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  /**
   * Stable slug id, e.g. "sql-development".
   */
  id: string;
  title: string;
  subtitle?: string | null;
  description: string;
  longDescription?: string | null;
  valueProposition?: string | null;
  station: number;
  /**
   * Lottie/icon filename (kept as string per Q3).
   */
  icon?: string | null;
  /**
   * SVG filename (kept as string per Q3).
   */
  svg?: string | null;
  lottieReverse?: boolean | null;
  visible?: boolean | null;
  deliverables?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  benefitHeadline?: string | null;
  impactMetric?: {
    value?: string | null;
    label?: string | null;
  };
  stack?: (string | TechStack)[] | null;
  /**
   * Auto-computed from project.services; edit on the Projects side.
   */
  relatedProjects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  slug: string;
  title: string;
  oneLiner: string;
  description: string;
  status: 'public' | 'private' | 'wip';
  featured?: boolean | null;
  tags?: string[] | null;
  /**
   * Service offerings this project fulfills. Authors the projects↔services edge.
   */
  services?: (string | Service)[] | null;
  /**
   * Tech items this project uses. Authors the projects↔tech-stack edge.
   */
  stack?: (string | TechStack)[] | null;
  repoUrl?: string | null;
  liveUrl?: string | null;
  readmeUrl?: string | null;
  /**
   * Project cover image. Uploads land in Vercel Blob.
   */
  image?: (number | null) | Media;
  sections?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  impactMetric?: {
    /**
     * e.g. "3x faster"
     */
    value?: string | null;
    /**
     * e.g. "avg query improvement"
     */
    label?: string | null;
    /**
     * Optional "before" value for comparison displays.
     */
    before?: string | null;
  };
  impactMetrics?:
    | {
        value: string;
        label: string;
        before?: string | null;
        id?: string | null;
      }[]
    | null;
  location?: string | null;
  environment?: string | null;
  version?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  slug: string;
  title: string;
  /**
   * Listing-card summary. 1-2 sentences.
   */
  excerpt: string;
  date: string;
  lang: 'en' | 'fr' | 'es';
  category: 'professional' | 'personal';
  /**
   * Free-string tags (D-rel-3).
   */
  tags?: string[] | null;
  animation?: ('draw' | 'morph' | 'draw-fill') | null;
  /**
   * SVG filename in yesid.dev assets (per Q5, stays as string in 18b).
   */
  svg?: string | null;
  /**
   * Custom override URL. Leave blank to use /blog/<slug>.
   */
  url?: string | null;
  external?: boolean | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stack-scenarios".
 */
export interface StackScenario {
  /**
   * Stable scenario id, e.g. "analytics-dashboard".
   */
  id: string;
  domains: (
    | 'data-engineering'
    | 'web-development'
    | 'mobile-development'
    | 'analytics-bi'
    | 'systems-programming'
    | 'devops-infra'
    | 'internal-tooling'
  )[];
  techs: (string | TechStack)[];
  relatedProjects?: (number | Project)[] | null;
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  techStack?: {
    /**
     * Allow clients to find tech-stack.
     */
    find?: boolean | null;
    /**
     * Allow clients to update tech-stack.
     */
    update?: boolean | null;
  };
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
  };
  projects?: {
    /**
     * Allow clients to find projects.
     */
    find?: boolean | null;
    /**
     * Allow clients to update projects.
     */
    update?: boolean | null;
  };
  blogPosts?: {
    /**
     * Allow clients to find blog-posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to update blog-posts.
     */
    update?: boolean | null;
  };
  stackScenarios?: {
    /**
     * Allow clients to find stack-scenarios.
     */
    find?: boolean | null;
    /**
     * Allow clients to update stack-scenarios.
     */
    update?: boolean | null;
  };
  homeContent?: {
    /**
     * Allow clients to find home-content global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update home-content global.
     */
    update?: boolean | null;
  };
  servicesPage?: {
    /**
     * Allow clients to find services-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update services-page global.
     */
    update?: boolean | null;
  };
  projectsPage?: {
    /**
     * Allow clients to find projects-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update projects-page global.
     */
    update?: boolean | null;
  };
  blogPage?: {
    /**
     * Allow clients to find blog-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update blog-page global.
     */
    update?: boolean | null;
  };
  techStackPage?: {
    /**
     * Allow clients to find tech-stack-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update tech-stack-page global.
     */
    update?: boolean | null;
  };
  aboutContent?: {
    /**
     * Allow clients to find about-content global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update about-content global.
     */
    update?: boolean | null;
  };
  contactContent?: {
    /**
     * Allow clients to find contact-content global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update contact-content global.
     */
    update?: boolean | null;
  };
  navLinks?: {
    /**
     * Allow clients to find nav-links global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update nav-links global.
     */
    update?: boolean | null;
  };
  errorPages?: {
    /**
     * Allow clients to find error-pages global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update error-pages global.
     */
    update?: boolean | null;
  };
  siteMeta?: {
    /**
     * Allow clients to find site-meta global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-meta global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tech-stack';
        value: string | TechStack;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'stack-scenarios';
        value: string | StackScenario;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack_select".
 */
export interface TechStackSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  layer?: T;
  domains?: T;
  icon?: T;
  proficiency?: T;
  relatedServices?: T;
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  longDescription?: T;
  valueProposition?: T;
  station?: T;
  icon?: T;
  svg?: T;
  lottieReverse?: T;
  visible?: T;
  deliverables?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  benefitHeadline?: T;
  impactMetric?:
    | T
    | {
        value?: T;
        label?: T;
      };
  stack?: T;
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  oneLiner?: T;
  description?: T;
  status?: T;
  featured?: T;
  tags?: T;
  services?: T;
  stack?: T;
  repoUrl?: T;
  liveUrl?: T;
  readmeUrl?: T;
  image?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  impactMetric?:
    | T
    | {
        value?: T;
        label?: T;
        before?: T;
      };
  impactMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        before?: T;
        id?: T;
      };
  location?: T;
  environment?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  date?: T;
  lang?: T;
  category?: T;
  tags?: T;
  animation?: T;
  svg?: T;
  url?: T;
  external?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stack-scenarios_select".
 */
export interface StackScenariosSelect<T extends boolean = true> {
  id?: T;
  domains?: T;
  techs?: T;
  relatedProjects?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  techStack?:
    | T
    | {
        find?: T;
        update?: T;
      };
  services?:
    | T
    | {
        find?: T;
        update?: T;
      };
  projects?:
    | T
    | {
        find?: T;
        update?: T;
      };
  blogPosts?:
    | T
    | {
        find?: T;
        update?: T;
      };
  stackScenarios?:
    | T
    | {
        find?: T;
        update?: T;
      };
  homeContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  servicesPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  projectsPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  blogPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  techStackPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  aboutContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  contactContent?:
    | T
    | {
        find?: T;
        update?: T;
      };
  navLinks?:
    | T
    | {
        find?: T;
        update?: T;
      };
  errorPages?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteMeta?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Home page — hero, manifesto, journey, proof reel, services grid, closer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  heroAnim: {
    scrollDown: string;
  };
  hero: {
    headline: {
      line1: string;
      line2: string;
      /**
       * Aria-label suffix so assistive tech hears the full headline.
       */
      ariaSuffix: string;
    };
    subheadline: string;
    subtitle: string;
    ctaWork: string;
    ctaContact: string;
    sqlPanel: {
      prompt: string;
      liveLabel: string;
      columns: {
        route: string;
        avgDelayS: string;
        vehicles: string;
      };
      /**
       * Template with {queryTime} and {updatedAgo} placeholders.
       */
      metaTemplate: string;
    };
    refreshButton: {
      label: string;
      helper: string;
    };
  };
  manifesto: {
    statement: {
      line1: string;
      lineHuge: string;
      line3Part1: string;
      line3Highlight: string;
      line3Part2: string;
    };
    terminal: {
      user: string;
      command: string;
    };
    pills?:
      | {
          label: string;
          /**
           * Service slug — not a relationship (free string, D-rel-3).
           */
          serviceId: string;
          id?: string | null;
        }[]
      | null;
    edgeLeft: {
      sectionNumber: string;
      sectionName: string;
      location: string;
    };
    edgeRight: {
      lat: string;
      lng: string;
      src: string;
      via: string;
      dst: string;
      node: string;
      status: string;
    };
    edgeBottom: {
      connected: string;
      line: string;
      url: string;
      version: string;
      scrollHint: string;
    };
    transit: {
      arrivalLabel: string;
      platformBadge: string;
      directionBadge: string;
    };
    /**
     * Hidden decorative transit lines rendered in the manifesto background.
     */
    hiddenTransitLines?:
      | {
          name: string;
          /**
           * Hex color code.
           */
          color: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Horizontal skills journey panels — each is a metro stop.
   */
  journey?:
    | {
        id: string;
        label: string;
        text: string;
        /**
         * Words within `text` that receive the highlight animation.
         */
        highlightWords?: string[] | null;
        highlightEffect: 'scale' | 'gradient' | 'wave' | 'charReveal';
        skills?:
          | {
              id: string;
              name: string;
              subtitle?: string | null;
              icon: 'sql' | 'typescript' | 'python' | 'sveltekit' | 'gsap' | 'powerbi' | 'docker';
            }[]
          | null;
      }[]
    | null;
  /**
   * CTA shown at the end of the skills journey strip.
   */
  journeyCta: {
    prompt: string;
    button: string;
  };
  /**
   * Proof / selected work reel section copy.
   */
  proofReel: {
    heading: string;
    headingDot: string;
    subheading: string;
    sectionLabel: string;
    viewAllLabel: string;
    viewAllHref: string;
    /**
     * Template with {title} placeholder.
     */
    toggleColorAria: string;
  };
  /**
   * Home-page services overview section copy.
   */
  servicesGrid: {
    heading: string;
    headingDot: string;
    subheading: string;
    /**
     * Template with {title} placeholder.
     */
    viewIllustrationAria: string;
    viewAllLink: string;
  };
  /**
   * TERMINUS / end-of-line closing section copy.
   */
  closer: {
    heading: string;
    headingDot: string;
    subheading: string;
    cta: {
      label: string;
      href: string;
    };
    rows: {
      contact: {
        label: string;
        description: string;
        action: string;
      };
      connect: {
        label: string;
        description: string;
        action: string;
      };
      read: {
        label: string;
        action: string;
      };
      about: {
        label: string;
        description: string;
        action: string;
      };
    };
    attribution: {
      text: string;
      url: string;
    };
    /**
     * Departure-board terminal chrome copy.
     */
    terminal: {
      title: string;
      city: string;
      encoding: string;
      /**
       * Template with {count} placeholder.
       */
      destinationsLabel: string;
      prompt: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /services route — listing page intro + listing chrome + detail page chrome.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  /**
   * HTML <title> + <meta description> for /services.
   */
  meta: {
    title: string;
    description: string;
  };
  /**
   * Services listing page chrome (ServiceListingPage, ServiceCard, ProjectsStrip).
   */
  listing: {
    heading: string;
    /**
     * Template: "Service {stationNum} / {totalStr}".
     */
    stationLabelTemplate: string;
    deepDiveLabel: string;
    projectsStrip: {
      /**
       * Template with {serviceTitle} placeholder.
       */
      builtWithService: string;
      builtWithFallback: string;
      projectSingular: string;
      projectPlural: string;
    };
  };
  /**
   * Service detail page chrome (ServiceDetailPage, ServiceNav).
   */
  detail: {
    backToServicesLabel: string;
    valuePropositionHeading: string;
    deliverablesHeading: string;
    relatedProjectsHeading: string;
    relatedProjectsNavAria: string;
    serviceNavAria: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /projects route — listing page intro + listing chrome + detail page chrome.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  /**
   * HTML <title> + <meta description> for /projects.
   */
  meta: {
    title: string;
    description: string;
  };
  /**
   * Projects listing page chrome (ProjectListingPage, ProjectFilterMobile, ProjectFilterSidebar, ProjectCard).
   */
  listing: {
    heading: string;
    searchPlaceholder: string;
    /**
     * "See all projects →" link — used from service detail pages.
     */
    seeAllLink: string;
    filters: {
      filtersLabel: string;
      services: string;
      tags: string;
      techStack: string;
      allLabel: string;
      /**
       * Prefix before the active filter label in mobile status.
       */
      showingPrefix: string;
    };
    card: {
      /**
       * Suffix after the first N stack items. Template: "+{count} more".
       */
      stackOverflowSuffix: string;
    };
  };
  /**
   * Project detail page chrome (ProjectDetailHeader, ProjectDetailPage, ProjectGlancePanel, ProjectTocPill).
   */
  detail: {
    backToListingLabel: string;
    tocSectionTitle: string;
    readmeSectionTitle: string;
    /**
     * Glance panel (desktop sidebar + mobile collapsible) section headings.
     */
    glance: {
      overview: string;
      impact: string;
      stack: string;
      services: string;
      links: string;
      /**
       * Mobile-only rolled-up heading.
       */
      projectInfo: string;
      liveSiteLabel: string;
      /**
       * Mobile variant: "↗ Live Site".
       */
      liveSiteLabelMobile: string;
      githubLabel: string;
    };
    tocPill: {
      openAria: string;
      closeAria: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /blog route — listing page chrome (professional + personal streams) + detail page chrome.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  /**
   * Blog listing page chrome (BlogListingPage, BlogFilterMobile, BlogFilterSidebar, BlogRouteMap).
   */
  listing: {
    mobileHeading: string;
    searchPlaceholder: string;
    resultNoun: string;
    noPostsMessage: string;
    filters: {
      filtersLabel: string;
      allLabel: string;
      language: string;
      dateRange: string;
      from: string;
      to: string;
      tags: string;
      /**
       * Prefix before the active filter label in mobile status.
       */
      showingPrefix: string;
    };
    routeMap: {
      title: string;
      terminus: string;
    };
  };
  /**
   * Blog detail page chrome (BlogContent, BlogDetailHeader, BlogDetailPage, BlogTocPill).
   */
  detail: {
    /**
     * Code block copy-button chrome.
     */
    code: {
      copyAria: string;
      copyLabel: string;
      errorLabel: string;
    };
    /**
     * Back-nav link text in BlogDetailHeader, varies by category.
     */
    backNav: {
      toPersonal: string;
      toDispatches: string;
    };
    header: {
      postTagsAria: string;
      /**
       * Reading-time suffix. Template: "{minutes} min read".
       */
      readingTimeLabel: string;
    };
    /**
     * Desktop TOC toggle labels + metadata panel column labels.
     */
    page: {
      readingMode: string;
      tocSectionTitle: string;
      metaCategory: string;
      metaWords: string;
      metaReadTime: string;
      metaLanguage: string;
      metaTags: string;
    };
    /**
     * Mobile table-of-contents pill button labels.
     */
    tocPill: {
      openAria: string;
      closeAria: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /tech-stack page copy — hero, stats, CTA, meta.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack-page".
 */
export interface TechStackPage {
  id: number;
  /**
   * HTML <title> + <meta description> for /tech-stack.
   */
  meta: {
    title: string;
    /**
     * Template with {itemCount} + {layerCount} placeholders.
     */
    description: string;
  };
  /**
   * Hero section — overline, title lines, terminal aria, stat labels.
   */
  hero: {
    overline: string;
    /**
     * H1 line 1 — before the <br> break.
     */
    titleLine1: string;
    /**
     * H1 line 2 — inside the .hero-title-accent span. Trailing "." stays as a literal in the template.
     */
    titleLine2: string;
    terminalAria: string;
    /**
     * Stat labels beneath the count numbers.
     */
    stats: {
      technologies: string;
      layers: string;
      domains: string;
      projects: string;
    };
  };
  /**
   * Shared CTA button labels — rendered in both the hero bottom and CTA zone.
   */
  actions: {
    getInTouch: string;
    viewServices: string;
  };
  /**
   * Footer CTA zone — heading lines, sub-copy, availability label.
   */
  cta: {
    /**
     * H2 line 1. Trailing "?" accent stays as a literal span.
     */
    headingLine1: string;
    /**
     * H2 line 2. Trailing "." accent stays as a literal span.
     */
    headingLine2: string;
    sub: string;
    availability: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /about page — identity, metrics, methodology, testimonials, stack, interests, weather, client logos, CTA, stop labels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content".
 */
export interface AboutContent {
  id: number;
  identity: {
    name: string;
    title: string;
    valueProp: string;
    /**
     * Path to headshot image in /static/. Future: convert to Media relationship.
     */
    headshot?: string | null;
    polaroids?:
      | {
          src: string;
          alt: string;
          caption: string;
          rotate: number;
          id?: string | null;
        }[]
      | null;
  };
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  methodology?:
    | {
        id: string;
        station: number;
        label: string;
        description: string;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        role: string;
        company: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Categorized tech list used on the /about page. Parallel to the `tech-stack` collection but used for a different UI section.
   */
  techStack?:
    | {
        name: string;
        category: 'databases' | 'languages' | 'frameworks' | 'tools';
        /**
         * Service IDs this tech applies to. Free-string — not a relationship. Aligns with D-rel-3 tags pattern.
         */
        relatedServices?: string[] | null;
        id?: string | null;
      }[]
    | null;
  interests?:
    | {
        id: string;
        label: string;
        /**
         * Path to interest image. Future: convert to Media relationship.
         */
        image: string;
      }[]
    | null;
  weather: {
    city: string;
    hook: string;
    enabled?: boolean | null;
  };
  clientLogos?:
    | {
        name: string;
        /**
         * Path to logo SVG. Future: convert to Media relationship.
         */
        src: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Total client count displayed in the bento.
   */
  clientCount: number;
  cta: {
    /**
     * Terminal-style command string, non-localized for brand consistency.
     */
    command: string;
    lines?:
      | {
          text: string;
          color?: ('orange' | 'muted') | null;
          id?: string | null;
        }[]
      | null;
    buttonLabel: string;
    buttonHref: string;
    availability: string;
    socials?:
      | {
          label: string;
          href: string;
          icon: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * 10 ALL-CAPS bento card labels.
   */
  stopLabels: {
    identity: string;
    metrics: string;
    testimonials: string;
    process: string;
    stack: string;
    clients: string;
    interests: string;
    snapshots: string;
    location: string;
    next: string;
  };
  labels: {
    clientsServed: string;
    polaroidPrevAria: string;
    polaroidNextAria: string;
    testimonialsCarouselAria: string;
    testimonialsTabNavAria: string;
    testimonialSlideAria: string;
    showTestimonialAria: string;
  };
  meta: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /contact page — form terminals, validation, success states, socials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content".
 */
export interface ContactContent {
  id: number;
  pageTitle: string;
  stationLabel: string;
  sendErrorMessage: string;
  meta: {
    title: string;
    description: string;
  };
  infoTerminal: {
    /**
     * Terminal window title, brand-canonical across locales.
     */
    title: string;
    command: string;
    location: string;
    responseTime: string;
    sectionLabels: {
      location: string;
      connect: string;
    };
  };
  formTerminal: {
    title: string;
    command: string;
    commandOutput: string;
    fields: {
      name: {
        label: string;
        placeholder: string;
      };
      email: {
        label: string;
        placeholder: string;
      };
      message: {
        label: string;
        placeholder: string;
      };
    };
    submitLabel: string;
  };
  validation: {
    /**
     * Template with {field} placeholder.
     */
    required: string;
    invalidEmail: string;
    /**
     * Template with {count} placeholder.
     */
    errorSummary: string;
  };
  success: {
    validating: string;
    sending: string;
    sent: string;
    responseTime: string;
    /**
     * Template with {work} + {blog} link placeholders.
     */
    meanwhile: string;
    resetLabel: string;
    fieldOk: string;
  };
  socials?:
    | {
        label: string;
        href: string;
        icon: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Public web3forms endpoint ID. Not a secret (per spec Q8) despite the name.
   */
  web3formsKey: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Top navigation + menu overlay + shared chrome labels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-links".
 */
export interface NavLink {
  id: number;
  navLinks?:
    | {
        label: string;
        href: string;
        priority: '1' | '2';
        id?: string | null;
      }[]
    | null;
  menuItems?:
    | {
        label: string;
        href: string;
        subtitle: string;
        id?: string | null;
      }[]
    | null;
  metroBookends: {
    departure: string;
    featured: string;
    about: string;
    blog: string;
    terminal: string;
  };
  navDirections: {
    previous: string;
    next: string;
  };
  sharedChrome: {
    openMenuAria: string;
    closeMenuAria: string;
    footerNavAria: string;
    menuOverlayAria: string;
    menuOverlayFooterLabel: string;
    searchPlaceholder: string;
    clearFiltersLabel: string;
    tocToggleSectionAria: string;
    tocHeading: string;
    tocMobileButton: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 404 and other error page copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-pages".
 */
export interface ErrorPage {
  id: number;
  notFound: {
    label: string;
    heading: string;
    description: string;
    /**
     * Terminal-style status line. Not localized — identical across locales.
     */
    terminalLine: string;
    suggestions?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide metadata — brand name, tagline, description, and social/outreach links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta".
 */
export interface SiteMeta {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Used for <meta name="description">. Keep under 160 chars for SEO.
   */
  description?: string | null;
  links?: {
    email?: string | null;
    /**
     * Full https URL.
     */
    github?: string | null;
    /**
     * Full https URL.
     */
    linkedin?: string | null;
    /**
     * Full https URL.
     */
    upwork?: string | null;
  };
  /**
   * Footer chrome — tagline line, address line, status prefix. Rendered on every page.
   */
  footer: {
    /**
     * Mono decorative line under the wordmark, e.g. "// digital infrastructure".
     */
    tagline: string;
    /**
     * Address line with middot separator, e.g. "Montreal, QC · Remote".
     */
    location: string;
    /**
     * Prefix before system date in status bar, e.g. "system online —".
     */
    statusPrefix: string;
  };
  /**
   * Auto-set by beforeChange hook on every save; ISO timestamp.
   */
  deployedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  heroAnim?:
    | T
    | {
        scrollDown?: T;
      };
  hero?:
    | T
    | {
        headline?:
          | T
          | {
              line1?: T;
              line2?: T;
              ariaSuffix?: T;
            };
        subheadline?: T;
        subtitle?: T;
        ctaWork?: T;
        ctaContact?: T;
        sqlPanel?:
          | T
          | {
              prompt?: T;
              liveLabel?: T;
              columns?:
                | T
                | {
                    route?: T;
                    avgDelayS?: T;
                    vehicles?: T;
                  };
              metaTemplate?: T;
            };
        refreshButton?:
          | T
          | {
              label?: T;
              helper?: T;
            };
      };
  manifesto?:
    | T
    | {
        statement?:
          | T
          | {
              line1?: T;
              lineHuge?: T;
              line3Part1?: T;
              line3Highlight?: T;
              line3Part2?: T;
            };
        terminal?:
          | T
          | {
              user?: T;
              command?: T;
            };
        pills?:
          | T
          | {
              label?: T;
              serviceId?: T;
              id?: T;
            };
        edgeLeft?:
          | T
          | {
              sectionNumber?: T;
              sectionName?: T;
              location?: T;
            };
        edgeRight?:
          | T
          | {
              lat?: T;
              lng?: T;
              src?: T;
              via?: T;
              dst?: T;
              node?: T;
              status?: T;
            };
        edgeBottom?:
          | T
          | {
              connected?: T;
              line?: T;
              url?: T;
              version?: T;
              scrollHint?: T;
            };
        transit?:
          | T
          | {
              arrivalLabel?: T;
              platformBadge?: T;
              directionBadge?: T;
            };
        hiddenTransitLines?:
          | T
          | {
              name?: T;
              color?: T;
              id?: T;
            };
      };
  journey?:
    | T
    | {
        id?: T;
        label?: T;
        text?: T;
        highlightWords?: T;
        highlightEffect?: T;
        skills?:
          | T
          | {
              id?: T;
              name?: T;
              subtitle?: T;
              icon?: T;
            };
      };
  journeyCta?:
    | T
    | {
        prompt?: T;
        button?: T;
      };
  proofReel?:
    | T
    | {
        heading?: T;
        headingDot?: T;
        subheading?: T;
        sectionLabel?: T;
        viewAllLabel?: T;
        viewAllHref?: T;
        toggleColorAria?: T;
      };
  servicesGrid?:
    | T
    | {
        heading?: T;
        headingDot?: T;
        subheading?: T;
        viewIllustrationAria?: T;
        viewAllLink?: T;
      };
  closer?:
    | T
    | {
        heading?: T;
        headingDot?: T;
        subheading?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        rows?:
          | T
          | {
              contact?:
                | T
                | {
                    label?: T;
                    description?: T;
                    action?: T;
                  };
              connect?:
                | T
                | {
                    label?: T;
                    description?: T;
                    action?: T;
                  };
              read?:
                | T
                | {
                    label?: T;
                    action?: T;
                  };
              about?:
                | T
                | {
                    label?: T;
                    description?: T;
                    action?: T;
                  };
            };
        attribution?:
          | T
          | {
              text?: T;
              url?: T;
            };
        terminal?:
          | T
          | {
              title?: T;
              city?: T;
              encoding?: T;
              destinationsLabel?: T;
              prompt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  listing?:
    | T
    | {
        heading?: T;
        stationLabelTemplate?: T;
        deepDiveLabel?: T;
        projectsStrip?:
          | T
          | {
              builtWithService?: T;
              builtWithFallback?: T;
              projectSingular?: T;
              projectPlural?: T;
            };
      };
  detail?:
    | T
    | {
        backToServicesLabel?: T;
        valuePropositionHeading?: T;
        deliverablesHeading?: T;
        relatedProjectsHeading?: T;
        relatedProjectsNavAria?: T;
        serviceNavAria?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  listing?:
    | T
    | {
        heading?: T;
        searchPlaceholder?: T;
        seeAllLink?: T;
        filters?:
          | T
          | {
              filtersLabel?: T;
              services?: T;
              tags?: T;
              techStack?: T;
              allLabel?: T;
              showingPrefix?: T;
            };
        card?:
          | T
          | {
              stackOverflowSuffix?: T;
            };
      };
  detail?:
    | T
    | {
        backToListingLabel?: T;
        tocSectionTitle?: T;
        readmeSectionTitle?: T;
        glance?:
          | T
          | {
              overview?: T;
              impact?: T;
              stack?: T;
              services?: T;
              links?: T;
              projectInfo?: T;
              liveSiteLabel?: T;
              liveSiteLabelMobile?: T;
              githubLabel?: T;
            };
        tocPill?:
          | T
          | {
              openAria?: T;
              closeAria?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  listing?:
    | T
    | {
        mobileHeading?: T;
        searchPlaceholder?: T;
        resultNoun?: T;
        noPostsMessage?: T;
        filters?:
          | T
          | {
              filtersLabel?: T;
              allLabel?: T;
              language?: T;
              dateRange?: T;
              from?: T;
              to?: T;
              tags?: T;
              showingPrefix?: T;
            };
        routeMap?:
          | T
          | {
              title?: T;
              terminus?: T;
            };
      };
  detail?:
    | T
    | {
        code?:
          | T
          | {
              copyAria?: T;
              copyLabel?: T;
              errorLabel?: T;
            };
        backNav?:
          | T
          | {
              toPersonal?: T;
              toDispatches?: T;
            };
        header?:
          | T
          | {
              postTagsAria?: T;
              readingTimeLabel?: T;
            };
        page?:
          | T
          | {
              readingMode?: T;
              tocSectionTitle?: T;
              metaCategory?: T;
              metaWords?: T;
              metaReadTime?: T;
              metaLanguage?: T;
              metaTags?: T;
            };
        tocPill?:
          | T
          | {
              openAria?: T;
              closeAria?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack-page_select".
 */
export interface TechStackPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        overline?: T;
        titleLine1?: T;
        titleLine2?: T;
        terminalAria?: T;
        stats?:
          | T
          | {
              technologies?: T;
              layers?: T;
              domains?: T;
              projects?: T;
            };
      };
  actions?:
    | T
    | {
        getInTouch?: T;
        viewServices?: T;
      };
  cta?:
    | T
    | {
        headingLine1?: T;
        headingLine2?: T;
        sub?: T;
        availability?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        name?: T;
        title?: T;
        valueProp?: T;
        headshot?: T;
        polaroids?:
          | T
          | {
              src?: T;
              alt?: T;
              caption?: T;
              rotate?: T;
              id?: T;
            };
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  methodology?:
    | T
    | {
        id?: T;
        station?: T;
        label?: T;
        description?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        company?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        name?: T;
        category?: T;
        relatedServices?: T;
        id?: T;
      };
  interests?:
    | T
    | {
        id?: T;
        label?: T;
        image?: T;
      };
  weather?:
    | T
    | {
        city?: T;
        hook?: T;
        enabled?: T;
      };
  clientLogos?:
    | T
    | {
        name?: T;
        src?: T;
        id?: T;
      };
  clientCount?: T;
  cta?:
    | T
    | {
        command?: T;
        lines?:
          | T
          | {
              text?: T;
              color?: T;
              id?: T;
            };
        buttonLabel?: T;
        buttonHref?: T;
        availability?: T;
        socials?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              id?: T;
            };
      };
  stopLabels?:
    | T
    | {
        identity?: T;
        metrics?: T;
        testimonials?: T;
        process?: T;
        stack?: T;
        clients?: T;
        interests?: T;
        snapshots?: T;
        location?: T;
        next?: T;
      };
  labels?:
    | T
    | {
        clientsServed?: T;
        polaroidPrevAria?: T;
        polaroidNextAria?: T;
        testimonialsCarouselAria?: T;
        testimonialsTabNavAria?: T;
        testimonialSlideAria?: T;
        showTestimonialAria?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content_select".
 */
export interface ContactContentSelect<T extends boolean = true> {
  pageTitle?: T;
  stationLabel?: T;
  sendErrorMessage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  infoTerminal?:
    | T
    | {
        title?: T;
        command?: T;
        location?: T;
        responseTime?: T;
        sectionLabels?:
          | T
          | {
              location?: T;
              connect?: T;
            };
      };
  formTerminal?:
    | T
    | {
        title?: T;
        command?: T;
        commandOutput?: T;
        fields?:
          | T
          | {
              name?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              email?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              message?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
            };
        submitLabel?: T;
      };
  validation?:
    | T
    | {
        required?: T;
        invalidEmail?: T;
        errorSummary?: T;
      };
  success?:
    | T
    | {
        validating?: T;
        sending?: T;
        sent?: T;
        responseTime?: T;
        meanwhile?: T;
        resetLabel?: T;
        fieldOk?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  web3formsKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-links_select".
 */
export interface NavLinksSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        priority?: T;
        id?: T;
      };
  menuItems?:
    | T
    | {
        label?: T;
        href?: T;
        subtitle?: T;
        id?: T;
      };
  metroBookends?:
    | T
    | {
        departure?: T;
        featured?: T;
        about?: T;
        blog?: T;
        terminal?: T;
      };
  navDirections?:
    | T
    | {
        previous?: T;
        next?: T;
      };
  sharedChrome?:
    | T
    | {
        openMenuAria?: T;
        closeMenuAria?: T;
        footerNavAria?: T;
        menuOverlayAria?: T;
        menuOverlayFooterLabel?: T;
        searchPlaceholder?: T;
        clearFiltersLabel?: T;
        tocToggleSectionAria?: T;
        tocHeading?: T;
        tocMobileButton?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-pages_select".
 */
export interface ErrorPagesSelect<T extends boolean = true> {
  notFound?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        terminalLine?: T;
        suggestions?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-meta_select".
 */
export interface SiteMetaSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  links?:
    | T
    | {
        email?: T;
        github?: T;
        linkedin?: T;
        upwork?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        location?: T;
        statusPrefix?: T;
      };
  deployedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}